version: 0.2

env:
  variables:
    # ENV: "dev"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}

  build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/build_api.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/build_api.sh
      - docker images

  post_build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/postbuild_api.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/postbuild_api.sh

artifacts:
  files:
    - ${CODEBUILD_SRC_DIR}/codedeploy/appspec.yml
    - ${CODEBUILD_SRC_DIR}/codedeploy/taskdef.json
  discard-paths: yes
  name: BuildAPI
