version: 0.2

env:
  variables:
    ENV: "dev"
    SRC_LAND: "web"

phases:
  pre_build:
    commands:
      - ls -la ${CODEBUILD_SRC_DIR}/${SRC_LAND}/
      - echo "S3 LANDING PAGE ${S3_FRONT}"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}

  build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/web/build.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/web/build.sh

  post_build:
    commands:
      - chmod a+x ${CODEBUILD_SRC_DIR}/codebuild/web/postbuild.sh
      - ${CODEBUILD_SRC_DIR}/codebuild/web/postbuild.sh
