version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: prj-api-ecs-dev
          ContainerPort: 3000

Hooks:
  - AfterAllowTraffic: "lambda_alert_action"
